const db=window.supabase.createClient(window.BEAROPS_SUPABASE_URL,window.BEAROPS_SUPABASE_ANON_KEY),$=id=>document.getElementById(id);
const checklist=[
{cat:'Property Information',items:[['Customer / Property Info','Accurate records keep the home profile useful year after year.','Confirm contact, address, year built, size, and special systems.'],['Main Water Shutoff','Every homeowner should know how to shut water off quickly during a leak.','Locate, test accessibility, label, and photograph the shutoff.'],['Smoke / CO Detectors','Detectors have a service life and should be replaced when expired.','Check age, placement, and function.']]},
{cat:'Exterior',items:[['Gutters','Poor drainage can damage fascia, siding, and foundation areas.','Check debris, discharge locations, and splash blocks.'],['Downspouts','Downspouts should direct water away from the home.','Verify extensions and discharge areas.'],['Gutter Guards','Gutter guards still require monitoring and cleaning.','Check for debris buildup and overflow signs.'],['Splash Blocks','Splash blocks help prevent erosion near the foundation.','Recommend correction where drainage is too close.'],['Sealants / Caulking','Failed sealants allow water behind exterior surfaces.','Photograph failed joints and recommend replacement.'],['Paint / Exterior Finish','Paint protects trim and siding from moisture and UV damage.','Identify exposed or deteriorated areas.'],['Windows / Doors Exterior','Failed seals and gaps can allow air and water entry.','Check visible sealants, weatherstripping, and operation.']]},
{cat:'Roof',items:[['Roof Covering - Ground View','Aging roof materials increase water intrusion risk.','Document visible wear, missing shingles, debris, and penetrations.'],['Pipe Boots / Roof Penetrations','Cracked boots are a common roof leak source.','Flag for roofing partner if deterioration is visible.'],['Fascia / Soffit','Deteriorated fascia and soffit can indicate roof edge or ventilation problems.','Document rot, staining, pest openings, or displacement.']]},
{cat:'Plumbing',items:[['Water Heater','Older water heaters should be budgeted before failure.','Record age, condition, shutoff, pan, and drain path.'],['Toilets / Visible Leaks','Small toilet leaks can waste water and damage flooring.','Check loose toilets, running tanks, and supply lines.'],['Visible Sink Drains / P-Traps','Small drain leaks can damage cabinets and flooring.','Check accessible drains and note corrosion or seepage.'],['Supply Shutoffs','Accessible fixture shutoffs reduce damage during leaks.','Confirm accessible shutoffs where visible.']]},
{cat:'Electrical',items:[['Panel Exterior Review','Panel labeling and visible condition help future service work.','Photograph panel and note visible concerns only.'],['GFCI Protection','GFCI protection reduces shock risk in wet locations.','Test accessible GFCI devices and refer as needed.'],['Smoke / CO Power','Hardwired detectors should remain powered and current.','Check visible age and operation where accessible.']]},
{cat:'HVAC',items:[['Filter / Return Air','Clean filters protect comfort, efficiency, and equipment life.','Verify filter size and replacement schedule.'],['Condensate Drain','Clogged condensate drains can cause interior water damage.','Check visible drain condition and cleanout access.'],['Air Handler / Closet','Condensation, rust, or staining can warn of service needs.','Document visible condition and access.']]},
{cat:'Interior',items:[['Walls / Ceilings','Staining, cracking, or blistering can indicate leaks or movement.','Document visible stains, cracks, or soft areas.'],['Doors / Hardware','Poor operation can indicate settling, wear, or maintenance needs.','Check representative doors and hardware.']]},
{cat:'Garage / Laundry',items:[['Dryer Vent','Lint buildup can reduce performance and increase fire risk.','Document buildup and recommend cleaning.'],['Garage Door Safety','Garage doors are heavy moving systems and should operate safely.','Check basic operation and visible safety concerns.']]}
];
const flat=checklist.flatMap((s,si)=>s.items.map((it,ii)=>({cat:s.cat,title:it[0],education:it[1],defaultRec:it[2],sort:flatIndex(si,ii),num:`${si+1}.${ii+1}`})));
function flatIndex(si,ii){let n=0;for(let i=0;i<si;i++)n+=checklist[i].items.length;return n+ii}
let customers=[],properties=[],assessments=[],workOrders=[],photos=[],inspection=null,propertyId=null,customerId=null,categoryIds={},savedItems={},photoMap={},current=0,currentFilter='All';

function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function setView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
async function checkSession(){const {data}=await db.auth.getSession();data.session?showApp():showLogin()}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('refreshBtn').classList.add('hidden')}
async function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('refreshBtn').classList.remove('hidden');await loadAll()}
async function login(){const {error}=await db.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error){$('loginMsg').textContent=error.message;return}await showApp()}
async function logout(){await db.auth.signOut();location.reload()}

async function loadAll(){
 const [c,p,a,w,ph]=await Promise.all([
  db.from('customers').select('*').order('created_at',{ascending:false}),
  db.from('properties').select('*, customers(*)').order('created_at',{ascending:false}),
  db.from('assessments').select('*, properties(*, customers(*))').order('created_at',{ascending:false}),
  db.from('work_orders').select('*, properties(*)').order('created_at',{ascending:false}),
  db.from('photos').select('*').order('created_at',{ascending:false})
 ]);
 if(c.error||p.error||a.error||w.error){alert((c.error||p.error||a.error||w.error).message);return}
 customers=c.data||[];properties=p.data||[];assessments=a.data||[];workOrders=w.data||[];photos=ph.data||[];
 renderAll()
}
function renderAll(){renderCounts();renderSelects();renderCustomers();renderProperties();renderAssessments();renderWorkOrders()}
function renderCounts(){$('metricCustomers').textContent=customers.length;$('metricProperties').textContent=properties.length;$('metricAssessments').textContent=assessments.length;$('metricOpenWO').textContent=workOrders.filter(w=>w.status!=='complete').length}
function renderSelects(){const co=customers.map(c=>`<option value="${c.id}">${c.full_name}</option>`).join('');$('propertyCustomer').innerHTML=co;const po=properties.map(p=>`<option value="${p.id}">${p.address}</option>`).join('');$('assessmentProperty').innerHTML=po}
function row(title,body,actions=''){return`<div class="row"><h3>${title}</h3><div>${body}</div><div class="actions">${actions}</div></div>`}
function renderCustomers(){$('customerList').innerHTML=customers.map(c=>row(c.full_name,`${c.email||''}<br>${c.phone||''}<br><span class="muted">${c.notes||''}</span>`,`<button data-id="${c.id}" class="edit-customer">Edit</button>`)).join('')||'<p>No customers yet.</p>';document.querySelectorAll('.edit-customer').forEach(b=>b.onclick=()=>editCustomer(b.dataset.id))}
function renderProperties(){$('propertyList').innerHTML=properties.map(p=>row(p.address,`${p.city||''}, ${p.state||''} ${p.zip||''}<br>Owner: ${p.customers?.full_name||'—'}<br><span class="muted">${p.notes||''}</span>`,`<button data-id="${p.id}" class="open-property-file">Open Property File</button><button data-id="${p.id}" class="edit-property">Edit</button>`)).join('')||'<p>No properties yet.</p>';document.querySelectorAll('.edit-property').forEach(b=>b.onclick=()=>editProperty(b.dataset.id));document.querySelectorAll('.open-property-file').forEach(b=>b.onclick=()=>openPropertyFile(b.dataset.id))}
function renderAssessments(){const html=assessments.map(a=>`<div class="assessment-row"><h3>${a.properties?.address||'No address'}</h3><p>${a.properties?.customers?.full_name||'No customer'} • ${a.assessment_date||''}</p><p class="muted">Score: ${a.home_health_score??'—'} | Risk: ${a.risk_index??'—'} | Status: ${a.status||'draft'}</p><div class="actions"><button class="open-assessment" data-id="${a.id}">Open / Review</button><button class="delete-assessment danger" data-id="${a.id}">Delete</button></div></div>`).join('')||'<p>No assessments yet.</p>';$('assessmentList').innerHTML=html;$('dashboardAssessments').innerHTML=html;document.querySelectorAll('.open-assessment').forEach(b=>b.onclick=()=>openAssessment(b.dataset.id));document.querySelectorAll('.delete-assessment').forEach(b=>b.onclick=()=>deleteAssessment(b.dataset.id))}
function renderWorkOrders(){const html=workOrders.map(w=>row(w.title,`Property: ${w.properties?.address||'—'}<br>Status: ${w.status} | Priority: ${w.priority}<br>Hours: ${w.estimated_hours||0} | Cost: ${w.estimated_cost||'TBD'}<br><span class="muted">${w.description||''}</span>`,`<button data-id="${w.id}" data-status="scheduled" class="wo-status">Schedule</button><button data-id="${w.id}" data-status="complete" class="wo-status">Complete</button>`)).join('')||'<p>No work orders yet.</p>';$('workOrderList').innerHTML=html;$('dashboardWorkOrders').innerHTML=html;document.querySelectorAll('.wo-status').forEach(b=>b.onclick=()=>updateWOStatus(b.dataset.id,b.dataset.status))}

async function saveCustomer(){const payload={full_name:$('customerName').value,email:$('customerEmail').value,phone:$('customerPhone').value,notes:$('customerNotes').value};let error;if($('customerId').value)({error}=await db.from('customers').update(payload).eq('id',$('customerId').value));else({error}=await db.from('customers').insert(payload));if(error){alert(error.message);return}clearCustomer();toast('Customer saved');await loadAll()}
function editCustomer(id){const c=customers.find(x=>x.id===id);$('customerId').value=c.id;$('customerName').value=c.full_name||'';$('customerEmail').value=c.email||'';$('customerPhone').value=c.phone||'';$('customerNotes').value=c.notes||'';setView('customers')}
function clearCustomer(){['customerId','customerName','customerEmail','customerPhone','customerNotes'].forEach(id=>$(id).value='')}
async function saveProperty(){const payload={customer_id:$('propertyCustomer').value||null,address:$('propertyAddress').value,city:$('propertyCity').value,state:$('propertyState').value,zip:$('propertyZip').value,year_built:Number($('propertyYear').value)||null,square_feet:Number($('propertySqft').value)||null,property_type:$('propertyType').value,notes:$('propertyNotes').value};let error;if($('propertyId').value)({error}=await db.from('properties').update(payload).eq('id',$('propertyId').value));else({error}=await db.from('properties').insert(payload));if(error){alert(error.message);return}clearProperty();toast('Property saved');await loadAll()}
function editProperty(id){const p=properties.find(x=>x.id===id);$('propertyId').value=p.id;$('propertyCustomer').value=p.customer_id||'';$('propertyAddress').value=p.address||'';$('propertyCity').value=p.city||'';$('propertyState').value=p.state||'';$('propertyZip').value=p.zip||'';$('propertyYear').value=p.year_built||'';$('propertySqft').value=p.square_feet||'';$('propertyType').value=p.property_type||'';$('propertyNotes').value=p.notes||'';setView('properties')}
function clearProperty(){['propertyId','propertyAddress','propertyCity','propertyZip','propertyYear','propertySqft','propertyType','propertyNotes'].forEach(id=>$(id).value='')}

async function startExistingAssessment(){const pid=$('assessmentProperty').value;if(!pid){alert('Create a property first.');return}await createAssessment(pid,$('assessmentTech').value)}
async function quickStartAssessment(){if(!$('quickCustomer').value||!$('quickAddress').value){alert('Customer and address required.');return}const {data:c,error:ce}=await db.from('customers').insert({full_name:$('quickCustomer').value,email:$('quickEmail').value,phone:$('quickPhone').value}).select().single();if(ce){alert(ce.message);return}const {data:p,error:pe}=await db.from('properties').insert({customer_id:c.id,address:$('quickAddress').value,city:$('quickCity').value,state:$('quickState').value,zip:$('quickZip').value}).select().single();if(pe){alert(pe.message);return}await createAssessment(p.id,$('quickTech').value)}
async function createAssessment(pid,tech){const {data:a,error}=await db.from('assessments').insert({property_id:pid,technician:tech,assessment_date:new Date().toISOString().slice(0,10),assessment_type:'Home Health Assessment',status:'draft',home_health_score:100,risk_index:'Low',estimated_hours:0}).select().single();if(error){alert(error.message);return}await ensureCategories(a.id);await loadAll();await openAssessment(a.id);toast('Assessment started')}
async function ensureCategories(assessmentId){const {data:existing}=await db.from('assessment_categories').select('*').eq('assessment_id',assessmentId).order('sort_order');if(existing&&existing.length)return existing;for(let i=0;i<checklist.length;i++)await db.from('assessment_categories').insert({assessment_id:assessmentId,name:checklist[i].cat,sort_order:i});const {data}=await db.from('assessment_categories').select('*').eq('assessment_id',assessmentId).order('sort_order');return data||[]}
async function openAssessment(id){const {data:a,error}=await db.from('assessments').select('*, properties(*, customers(*))').eq('id',id).single();if(error){alert(error.message);return}inspection=a;propertyId=a.property_id;customerId=a.properties?.customer_id;categoryIds={};savedItems={};photoMap={};current=0;const cats=await ensureCategories(id);cats.forEach(c=>categoryIds[c.name]=c.id);const {data:items,error:ie}=await db.from('assessment_items').select('*').in('category_id',cats.map(c=>c.id)).order('sort_order');if(ie){alert(ie.message);return}items.forEach(i=>savedItems[i.sort_order]=i);photos.filter(p=>p.assessment_id===id).forEach(p=>{if(!p.assessment_item_id)return;(photoMap[p.assessment_item_id] ||= []).push(p)});$('sidePropertyName').textContent=a.properties?.address||'';$('sideAssessmentName').textContent='Initial Bear Assessment';$('inspectionEditor').classList.remove('hidden');setView('assessments');renderSide();renderItem();summary();$('reportText').value=a.summary||''}
async function saveInspectionMeta(){toast('Inspection info saved')}
async function deleteAssessment(id){if(!confirm('Delete this inspection and related work orders/photos?'))return;const cats=await ensureCategories(id);const catIds=cats.map(c=>c.id);if(catIds.length){const {data:items}=await db.from('assessment_items').select('id').in('category_id',catIds);const ids=(items||[]).map(i=>i.id);if(ids.length){await db.from('work_orders').delete().in('assessment_item_id',ids);await db.from('photos').delete().in('assessment_item_id',ids)}await db.from('assessment_items').delete().in('category_id',catIds)}await db.from('assessment_categories').delete().eq('assessment_id',id);await db.from('assessments').delete().eq('id',id);$('inspectionEditor').classList.add('hidden');toast('Inspection deleted');await loadAll()}
function renderSide(){let start=0;$('sideSections').innerHTML=checklist.map((s,i)=>{const total=s.items.length,done=s.items.filter((_,idx)=>savedItems[start+idx]).length,myStart=start;start+=total;return`<div class="side-section" data-start="${myStart}"><span><b class="side-num">${i+1}</b> ${s.cat}</span><small>${done}/${total}</small></div>`}).join('');document.querySelectorAll('.side-section').forEach(b=>b.onclick=()=>{current=Number(b.dataset.start);renderItem()})}
function statusDefaults(s){return s==='Good'?{risk:0,hours:0}:s==='Monitor'?{risk:2,hours:.25}:s==='Service Soon'?{risk:4,hours:.75}:s==='Critical'?{risk:10,hours:2}:{risk:7,hours:1.5}}
function renderSectionList(){const item=flat[current],section=checklist.find(s=>s.cat===item.cat),start=flat.findIndex(f=>f.cat===item.cat);let list=section.items.map((it,idx)=>flat[start+idx]);let term=$('itemSearch').value?.toLowerCase()||'';list=list.filter(f=>!term||f.title.toLowerCase().includes(term));list=list.filter(f=>currentFilter==='All'||(savedItems[f.sort]?.status||'Good')===currentFilter);$('sectionItemList').innerHTML=list.map(f=>{const saved=savedItems[f.sort],status=saved?.status||'Good',pc=saved?.id?(photoMap[saved.id]||[]).length:0;return`<div class="bt-list-item ${f.sort===current?'active':''}" data-sort="${f.sort}"><span class="item-no">${f.num}</span><div class="item-main"><strong>${f.title}</strong><small>Bear Home Management</small></div><span><b class="status-pill status-${status.replaceAll(' ','-')}">${status}</b><span class="mini-photo">📷 ${pc}</span></span></div>`}).join('')||'<p class="card">No items match.</p>';document.querySelectorAll('.bt-list-item').forEach(b=>b.onclick=()=>{current=Number(b.dataset.sort);renderItem()})}
function renderItem(){const item=flat[current],ex=savedItems[current]||{},status=ex.status||'Good';$('sectionTitle').textContent=`Section ${item.num.split('.')[0]}: ${item.cat}`;$('categoryLabel').textContent=item.cat;$('itemTitle').textContent=item.title;$('detailNumber').textContent=item.num;$('educationText').textContent=item.education;$('itemCounter').textContent=`${Object.keys(savedItems).length} of ${flat.length} items completed`;$('detailStatus').textContent=status;$('detailStatus').className=`status-pill status-${status.replaceAll(' ','-')}`;document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b.dataset.status===status));document.querySelectorAll('.side-section').forEach(b=>b.classList.toggle('active',flat[Number(b.dataset.start)]?.cat===item.cat));$('riskPoints').value=ex.risk_points??0;$('estimatedHours').value=ex.estimated_hours??0;$('costRange').value=ex.cost_range||'';$('workOrderNeeded').value=ex.work_order_needed?'Yes':'No';$('observation').value=ex.observation||'';$('answerObserve').value=ex.observation||'';$('answerMeaning').value=ex.homeowner_education||item.education;$('recommendation').value=ex.recommendation||item.defaultRec;$('whenField').value=ex.when_note||'';renderPhotos();renderSide();renderSectionList();previewScore()}
function chooseStatus(s){const d=statusDefaults(s);$('riskPoints').value=d.risk;$('estimatedHours').value=d.hours;$('workOrderNeeded').value=(s==='Needs Repair'||s==='Critical')?'Yes':'No';document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b.dataset.status===s));$('detailStatus').textContent=s;$('detailStatus').className=`status-pill status-${s.replaceAll(' ','-')}`;previewScore()}
async function saveItem(){const item=flat[current],active=document.querySelector('.choice.active'),status=active?active.dataset.status:'Good',payload={category_id:categoryIds[item.cat],title:item.title,status,risk_points:Number($('riskPoints').value)||0,estimated_hours:Number($('estimatedHours').value)||0,observation:$('observation').value||$('answerObserve').value,homeowner_education:$('answerMeaning').value||item.education,recommendation:$('recommendation').value,cost_range:$('costRange').value,work_order_needed:$('workOrderNeeded').value==='Yes',sort_order:current};let data,error;if(savedItems[current]?.id)({data,error}=await db.from('assessment_items').update(payload).eq('id',savedItems[current].id).select().single());else({data,error}=await db.from('assessment_items').insert(payload).select().single());if(error){alert(error.message);return null}savedItems[current]=data;await updateTotals();toast('Item saved');return data}
async function nextItem(){if(await saveItem()){if(current<flat.length-1){current++;renderItem()}else summary()}}
function calc(){const items=Object.values(savedItems),risk=items.reduce((s,i)=>s+(Number(i.risk_points)||0),0),hours=items.reduce((s,i)=>s+(Number(i.estimated_hours)||0),0),score=Math.max(0,100-risk),riskIndex=risk<=8?'Low':risk<=20?'Moderate':'High';return{items,risk,hours,score,riskIndex,wo:items.filter(i=>i.work_order_needed).length}}
function previewScore(){$('liveScore')&&($('liveScore').textContent=calc().score)}
async function updateTotals(){const t=calc();await db.from('assessments').update({home_health_score:t.score,risk_index:t.riskIndex,estimated_hours:t.hours}).eq('id',inspection.id);summary();await loadAll()}
function summary(){const t=calc();let pct=Math.round((Object.keys(savedItems).length/flat.length)*100);$('sideProgressPercent').textContent=pct+'%';$('sideBarFill').style.width=pct+'%'}
function generateReport(){const t=calc();let txt=`BearTrack™ Home Health Assessment\nPrepared by Bear Home Management\n\nProperty: ${$('sidePropertyName').textContent}\n\nHome Health Score: ${t.score}\nRisk Index: ${t.riskIndex}\nEstimated Home Care Hours: ${t.hours.toFixed(1)}\nWork Orders Recommended: ${t.wo}\n\nFindings:\n`;t.items.filter(i=>i.status!=='Good').forEach(i=>{txt+=`\n[${i.status}] ${i.title}\nObservation: ${i.observation||'No observation entered.'}\nWhy it matters: ${i.homeowner_education}\nRecommendation: ${i.recommendation}\nCost range: ${i.cost_range||'TBD'}\nPhotos: ${(photoMap[i.id]||[]).length}\n`});$('reportText').value=txt;db.from('assessments').update({summary:txt,status:'complete'}).eq('id',inspection.id);setView('report');toast('Report updated')}
async function createWorkOrders(){const t=calc();for(const i of t.items.filter(x=>x.work_order_needed)){const {data:existing}=await db.from('work_orders').select('id').eq('assessment_item_id',i.id);if(!existing?.length)await db.from('work_orders').insert({property_id:propertyId,assessment_item_id:i.id,title:i.title,description:i.observation,priority:i.risk_points>=7?'high':'normal',status:'open',estimated_hours:i.estimated_hours,estimated_cost:i.cost_range})}toast('Work orders created');await loadAll();setView('workorders')}
async function handlePhotos(files){let item=savedItems[current]||await saveItem();if(!item)return;for(const file of files){const dataUrl=await fileToDataUrl(file);const {data,error}=await db.from('photos').insert({property_id:propertyId,assessment_id:inspection.id,assessment_item_id:item.id,file_url:dataUrl,caption:item.title}).select().single();if(error){alert(error.message);return}(photoMap[item.id] ||= []).push(data)}toast('Photo added');renderPhotos();renderSectionList()}
function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function renderPhotos(){const item=savedItems[current],arr=item?(photoMap[item.id]||[]):[];$('photoCount').textContent=arr.length;$('photoPreview').innerHTML=arr.map(p=>`<img class="photo-thumb" src="${p.file_url}" alt="inspection photo">`).join('')+(arr.length?'':'<p class="photo-note">No photos yet.</p>')}
function openPropertyFile(id){const p=properties.find(x=>x.id===id);if(!p)return;const propA=assessments.filter(a=>a.property_id===id),wo=workOrders.filter(w=>w.property_id===id),open=wo.filter(w=>w.status!=='complete'),done=wo.filter(w=>w.status==='complete'),latest=propA[0];$('propertyFileTitle').textContent=p.address;$('propertyFileSub').textContent=`${p.city||''}, ${p.state||''} ${p.zip||''} • Owner: ${p.customers?.full_name||'—'}`;$('pfScore').textContent=latest?.home_health_score??'—';$('pfOpenWO').textContent=open.length;$('pfCompletedWO').textContent=done.length;$('pfAssessments').textContent=propA.length;$('pfOpenWorkOrders').innerHTML=open.map(w=>row(w.title,`Status: ${w.status}<br>${w.description||''}`)).join('')||'<p>No open work orders.</p>';$('pfCompletedWorkOrders').innerHTML=done.map(w=>row(w.title,`Completed: ${w.completed_at?new Date(w.completed_at).toLocaleDateString():'—'}<br>${w.description||''}`)).join('')||'<p>No completed work orders.</p>';$('pfAssessmentHistory').innerHTML=propA.map(a=>row(`${a.assessment_type||'Assessment'} - ${a.assessment_date||''}`,`Score: ${a.home_health_score??'—'} | Risk: ${a.risk_index??'—'}`,`<button data-id="${a.id}" class="pf-open">Open</button>`)).join('')||'<p>No inspections.</p>';document.querySelectorAll('.pf-open').forEach(b=>b.onclick=()=>openAssessment(b.dataset.id));setView('propertyfile')}
async function updateWOStatus(id,status){await db.from('work_orders').update({status,completed_at:status==='complete'?new Date().toISOString():null}).eq('id',id);toast('Work order updated');await loadAll()}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>chooseStatus(b.dataset.status));
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSectionList()});
$('itemSearch').oninput=renderSectionList;
$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('refreshBtn').onclick=loadAll;$('dashNewInspection').onclick=()=>setView('assessments');$('dashNewCustomer').onclick=()=>setView('customers');$('dashWorkOrders').onclick=()=>setView('workorders');
$('saveCustomerBtn').onclick=saveCustomer;$('clearCustomerBtn').onclick=clearCustomer;$('savePropertyBtn').onclick=saveProperty;$('clearPropertyBtn').onclick=clearProperty;$('startAssessmentBtn').onclick=startExistingAssessment;$('quickStartAssessmentBtn').onclick=quickStartAssessment;
$('saveInspectionMetaBtn').onclick=saveInspectionMeta;$('deleteAssessmentBtn').onclick=()=>deleteAssessment(inspection.id);$('saveItemBtn').onclick=saveItem;$('generateReportBtn').onclick=generateReport;$('createWorkOrdersBtn').onclick=createWorkOrders;$('photoInput').onchange=e=>handlePhotos([...e.target.files]);
checkSession();
