const db=window.supabase.createClient(window.BEAROPS_SUPABASE_URL,window.BEAROPS_SUPABASE_ANON_KEY),$=id=>document.getElementById(id);
const checklist=[
{cat:'Property & Safety',items:[['Customer / Property Info','Accurate records keep the home profile useful year after year.','Confirm contact, address, year built, size, and special systems.'],['Main Water Shutoff','Every homeowner should know how to shut water off quickly during a leak.','Locate, test accessibility, label, and photograph the shutoff.'],['Smoke / CO Detectors','Detectors have a service life and should be replaced when expired.','Check age, placement, and function.']]},
{cat:'Exterior',items:[['Gutters & Downspouts','Poor drainage can damage fascia, siding, and foundation areas.','Check debris, discharge locations, and splash blocks.'],['Sealants / Caulking','Failed sealants allow water behind exterior surfaces.','Photograph failed joints and recommend replacement.'],['Paint / Exterior Finish','Paint protects trim and siding from moisture and UV damage.','Identify exposed or deteriorated areas.']]},
{cat:'Roof',items:[['Roof Covering - Ground View','Aging roof materials increase water intrusion risk.','Document visible wear, missing shingles, debris, and penetrations.'],['Pipe Boots / Roof Penetrations','Cracked boots are a common roof leak source.','Flag for roofing partner if deterioration is visible.']]},
{cat:'Plumbing',items:[['Water Heater','Older water heaters should be budgeted before failure.','Record age, condition, shutoff, pan, and drain path.'],['Toilets / Visible Leaks','Small toilet leaks can waste water and damage flooring.','Check loose toilets, running tanks, and supply lines.'],['Visible Sink Drains / P-Traps','Small drain leaks can damage cabinets and flooring.','Check accessible drains and note corrosion or seepage.']]},
{cat:'Electrical',items:[['Panel Exterior Review','Panel labeling and visible condition help future service work.','Photograph panel and note visible concerns only.'],['GFCI Protection','GFCI protection reduces shock risk in wet locations.','Test accessible GFCI devices and refer as needed.']]},
{cat:'HVAC',items:[['Filter / Return Air','Clean filters protect comfort, efficiency, and equipment life.','Verify filter size and replacement schedule.'],['Condensate Drain','Clogged condensate drains can cause interior water damage.','Check visible drain condition and cleanout access.']]}
];
let flat=checklist.flatMap((s,si)=>s.items.map((it,ii)=>({cat:s.cat,title:it[0],education:it[1],defaultRec:it[2],sectionIndex:si,itemIndex:ii}))),current=0,inspection=null,categoryIds={},savedItems={},propertyId=null;
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function checkSession(){const {data}=await db.auth.getSession();data.session?showApp():showLogin()}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden')}
async function login(){const {error}=await db.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error){$('loginMsg').textContent=error.message;return}showApp()}
async function logout(){await db.auth.signOut();location.reload()}
async function startInspection(){
 if(!$('customerName').value.trim()||!$('propertyAddress').value.trim()){alert('Customer name and property address required.');return}
 const {data:cust,error:ce}=await db.from('customers').insert({full_name:$('customerName').value,email:$('customerEmail').value,phone:$('customerPhone').value}).select().single();if(ce){alert(ce.message);return}
 const {data:prop,error:pe}=await db.from('properties').insert({customer_id:cust.id,address:$('propertyAddress').value,city:$('propertyCity').value,state:$('propertyState').value,zip:$('propertyZip').value}).select().single();if(pe){alert(pe.message);return}
 propertyId=prop.id;
 const {data:ass,error:ae}=await db.from('assessments').insert({property_id:prop.id,technician:$('technician').value,assessment_date:new Date().toISOString().slice(0,10),assessment_type:'Home Health Assessment',status:'draft',home_health_score:100,risk_index:'Low',estimated_hours:0}).select().single();if(ae){alert(ae.message);return}
 inspection=ass;
 for(let i=0;i<checklist.length;i++){const {data:cat,error}=await db.from('assessment_categories').insert({assessment_id:inspection.id,name:checklist[i].cat,sort_order:i}).select().single();if(error){alert(error.message);return}categoryIds[checklist[i].cat]=cat.id}
 $('setupCard').classList.add('hidden');$('inspectionCard').classList.remove('hidden');renderItem();toast('Inspection started')
}
function statusDefaults(s){return s==='Good'?{risk:0,hours:0}:s==='Monitor'?{risk:2,hours:.25}:s==='Service Soon'?{risk:4,hours:.75}:{risk:7,hours:1.5}}
function renderItem(){const item=flat[current],ex=savedItems[current]||{};$('sectionTitle').textContent=item.cat;$('categoryLabel').textContent=item.cat;$('itemTitle').textContent=item.title;$('educationText').textContent=item.education;$('itemCounter').textContent=`Item ${current+1} of ${flat.length}`;$('bar').style.width=(current/flat.length*100)+'%';document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b.dataset.status===(ex.status||'')));$('riskPoints').value=ex.risk_points??0;$('estimatedHours').value=ex.estimated_hours??0;$('costRange').value=ex.cost_range||'';$('workOrderNeeded').value=ex.work_order_needed?'Yes':'No';$('observation').value=ex.observation||'';$('recommendation').value=ex.recommendation||item.defaultRec;updateScorePreview()}
function chooseStatus(s){const d=statusDefaults(s);$('riskPoints').value=d.risk;$('estimatedHours').value=d.hours;$('workOrderNeeded').value=s==='Needs Repair'?'Yes':'No';document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b.dataset.status===s));updateScorePreview()}
async function saveItem(){const item=flat[current],active=document.querySelector('.choice.active'),status=active?active.dataset.status:'Good',payload={category_id:categoryIds[item.cat],title:item.title,status,risk_points:Number($('riskPoints').value)||0,estimated_hours:Number($('estimatedHours').value)||0,observation:$('observation').value,homeowner_education:item.education,recommendation:$('recommendation').value,cost_range:$('costRange').value,work_order_needed:$('workOrderNeeded').value==='Yes',sort_order:current};let data,error;if(savedItems[current]?.id)({data,error}=await db.from('assessment_items').update(payload).eq('id',savedItems[current].id).select().single());else({data,error}=await db.from('assessment_items').insert(payload).select().single());if(error){alert(error.message);return false}savedItems[current]=data;await updateAssessmentTotals();toast('Item saved');return true}
async function next(){if(await saveItem()){if(current<flat.length-1){current++;renderItem()}else finishInspection()}}
function prev(){if(current>0){current--;renderItem()}}
function calcTotals(){const items=Object.values(savedItems),risk=items.reduce((s,i)=>s+(Number(i.risk_points)||0),0),hours=items.reduce((s,i)=>s+(Number(i.estimated_hours)||0),0),score=Math.max(0,100-risk),riskIndex=risk<=8?'Low':risk<=20?'Moderate':'High';return{items,risk,hours,score,riskIndex,wo:items.filter(i=>i.work_order_needed).length}}
function updateScorePreview(){$('score').textContent=calcTotals().score}
async function updateAssessmentTotals(){const t=calcTotals();$('score').textContent=t.score;await db.from('assessments').update({home_health_score:t.score,risk_index:t.riskIndex,estimated_hours:t.hours}).eq('id',inspection.id)}
function finishInspection(){$('bar').style.width='100%';$('finishCard').classList.remove('hidden');const t=calcTotals();$('finalScore').textContent=t.score;$('finalRisk').textContent=t.riskIndex;$('finalHours').textContent=t.hours.toFixed(1);$('finalWO').textContent=t.wo}
function generateReport(){const t=calcTotals();let txt=`Bear Home Management - Home Health Assessment\n\nHome Health Score: ${t.score}\nRisk Index: ${t.riskIndex}\nEstimated Home Care Hours: ${t.hours.toFixed(1)}\nWork Orders Recommended: ${t.wo}\n\nFindings:\n`;t.items.filter(i=>i.status!=='Good').forEach(i=>{txt+=`\n[${i.status}] ${i.title}\nObservation: ${i.observation||'No observation entered.'}\nWhy it matters: ${i.homeowner_education}\nRecommendation: ${i.recommendation}\nCost range: ${i.cost_range||'TBD'}\n`});$('reportText').value=txt;db.from('assessments').update({summary:txt,status:'complete'}).eq('id',inspection.id)}
async function createWorkOrders(){const t=calcTotals();for(const i of t.items.filter(x=>x.work_order_needed))await db.from('work_orders').insert({property_id:propertyId,assessment_item_id:i.id,title:i.title,description:i.observation,priority:i.risk_points>=7?'high':'normal',status:'open',estimated_hours:i.estimated_hours,estimated_cost:i.cost_range});toast('Work orders created')}
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>chooseStatus(b.dataset.status));$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('startBtn').onclick=startInspection;$('saveItemBtn').onclick=saveItem;$('nextBtn').onclick=next;$('prevBtn').onclick=prev;$('generateReportBtn').onclick=generateReport;$('createWorkOrdersBtn').onclick=createWorkOrders;checkSession();
