
const db=window.supabase.createClient(window.BEAROPS_SUPABASE_URL,window.BEAROPS_SUPABASE_ANON_KEY),$=id=>document.getElementById(id);
const checklist=[
{cat:'Property & Safety',items:[['Customer / Property Info','Accurate records keep the home profile useful year after year.','Confirm contact, address, year built, size, and special systems.'],['Main Water Shutoff','Every homeowner should know how to shut water off quickly during a leak.','Locate, test accessibility, label, and photograph the shutoff.'],['Smoke / CO Detectors','Detectors have a service life and should be replaced when expired.','Check age, placement, and function.']]},
{cat:'Exterior',items:[['Gutters & Downspouts','Poor drainage can damage fascia, siding, and foundation areas.','Check debris, discharge locations, and splash blocks.'],['Sealants / Caulking','Failed sealants allow water behind exterior surfaces.','Photograph failed joints and recommend replacement.'],['Paint / Exterior Finish','Paint protects trim and siding from moisture and UV damage.','Identify exposed or deteriorated areas.']]},
{cat:'Roof',items:[['Roof Covering - Ground View','Aging roof materials increase water intrusion risk.','Document visible wear, missing shingles, debris, and penetrations.'],['Pipe Boots / Roof Penetrations','Cracked boots are a common roof leak source.','Flag for roofing partner if deterioration is visible.']]},
{cat:'Plumbing',items:[['Water Heater','Older water heaters should be budgeted before failure.','Record age, condition, shutoff, pan, and drain path.'],['Toilets / Visible Leaks','Small toilet leaks can waste water and damage flooring.','Check loose toilets, running tanks, and supply lines.'],['Visible Sink Drains / P-Traps','Small drain leaks can damage cabinets and flooring.','Check accessible drains and note corrosion or seepage.']]},
{cat:'Electrical',items:[['Panel Exterior Review','Panel labeling and visible condition help future service work.','Photograph panel and note visible concerns only.'],['GFCI Protection','GFCI protection reduces shock risk in wet locations.','Test accessible GFCI devices and refer as needed.']]},
{cat:'HVAC',items:[['Filter / Return Air','Clean filters protect comfort, efficiency, and equipment life.','Verify filter size and replacement schedule.'],['Condensate Drain','Clogged condensate drains can cause interior water damage.','Check visible drain condition and cleanout access.']]}
];
let flat=checklist.flatMap((s,si)=>s.items.map((it,ii)=>({cat:s.cat,title:it[0],education:it[1],defaultRec:it[2],sectionIndex:si,itemIndex:ii}))),current=0,inspection=null,categoryIds={},savedItems={},propertyId=null,customerId=null;
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function setView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
async function checkSession(){const {data}=await db.auth.getSession();data.session?showApp():showLogin()}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')}
async function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await loadAssessments()}
async function login(){const {error}=await db.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error){$('loginMsg').textContent=error.message;return}showApp()}
async function logout(){await db.auth.signOut();location.reload()}
async function loadAssessments(){
 const {data,error}=await db.from('assessments').select('*, properties(*, customers(*))').order('created_at',{ascending:false});
 if(error){alert(error.message);return}
 $('assessmentList').innerHTML=(data||[]).map(a=>`<div class="assessment-row"><h3>${a.properties?.address||'No address'}</h3><p>${a.properties?.customers?.full_name||'No customer'} • ${a.assessment_date||''}</p><p class="muted">Score: ${a.home_health_score??'—'} | Risk: ${a.risk_index??'—'} | Status: ${a.status||'draft'}</p><div class="btnrow"><button class="open-assessment" data-id="${a.id}">Open / Review</button><button class="delete-assessment danger" data-id="${a.id}">Delete</button></div></div>`).join('')||'<p>No assessments saved yet.</p>';
 document.querySelectorAll('.open-assessment').forEach(btn=>btn.onclick=()=>openAssessment(btn.dataset.id));
 document.querySelectorAll('.delete-assessment').forEach(btn=>btn.onclick=()=>deleteAssessment(btn.dataset.id));
}
async function startInspection(){
 if(!$('customerName').value.trim()||!$('propertyAddress').value.trim()){alert('Customer name and property address required.');return}
 const {data:cust,error:ce}=await db.from('customers').insert({full_name:$('customerName').value,email:$('customerEmail').value,phone:$('customerPhone').value}).select().single();if(ce){alert(ce.message);return}
 const {data:prop,error:pe}=await db.from('properties').insert({customer_id:cust.id,address:$('propertyAddress').value,city:$('propertyCity').value,state:$('propertyState').value,zip:$('propertyZip').value}).select().single();if(pe){alert(pe.message);return}
 const {data:ass,error:ae}=await db.from('assessments').insert({property_id:prop.id,technician:$('technician').value,assessment_date:new Date().toISOString().slice(0,10),assessment_type:'Home Health Assessment',status:'draft',home_health_score:100,risk_index:'Low',estimated_hours:0}).select().single();if(ae){alert(ae.message);return}
 for(let i=0;i<checklist.length;i++){const {error}=await db.from('assessment_categories').insert({assessment_id:ass.id,name:checklist[i].cat,sort_order:i});if(error){alert(error.message);return}}
 await openAssessment(ass.id);toast('Inspection started')
}
async function openAssessment(id){
 const {data:ass,error}=await db.from('assessments').select('*, properties(*, customers(*))').eq('id',id).single();if(error){alert(error.message);return}
 inspection=ass;propertyId=ass.property_id;customerId=ass.properties?.customer_id;current=0;categoryIds={};savedItems={};
 const {data:cats,error:ce}=await db.from('assessment_categories').select('*').eq('assessment_id',id).order('sort_order');if(ce){alert(ce.message);return}
 if(!cats||!cats.length){alert('This assessment has no categories yet. Delete this test assessment and start a new one.');return} cats.forEach(c=>categoryIds[c.name]=c.id);
 const {data:items,error:ie}=await db.from('assessment_items').select('*').in('category_id',cats.map(c=>c.id)).order('sort_order');if(ie){alert(ie.message);return}
 items.forEach(i=>savedItems[i.sort_order]=i);
 $('editCustomerName').value=ass.properties?.customers?.full_name||'';$('editCustomerEmail').value=ass.properties?.customers?.email||'';$('editCustomerPhone').value=ass.properties?.customers?.phone||'';$('editPropertyAddress').value=ass.properties?.address||'';$('editPropertyCity').value=ass.properties?.city||'';$('editPropertyState').value=ass.properties?.state||'';$('editPropertyZip').value=ass.properties?.zip||'';$('editTechnician').value=ass.technician||'';
 $('openTitle').textContent=ass.properties?.address||'Open Assessment';$('openSub').textContent=(ass.properties?.customers?.full_name||'')+' • '+(ass.assessment_date||'');
 $('emptyEditor').classList.add('hidden');$('editor').classList.remove('hidden');setView('inspectView');renderItem();finishInspection();$('reportText').value=ass.summary||'';
}
async function saveMeta(){await db.from('customers').update({full_name:$('editCustomerName').value,email:$('editCustomerEmail').value,phone:$('editCustomerPhone').value}).eq('id',customerId);await db.from('properties').update({address:$('editPropertyAddress').value,city:$('editPropertyCity').value,state:$('editPropertyState').value,zip:$('editPropertyZip').value}).eq('id',propertyId);await db.from('assessments').update({technician:$('editTechnician').value}).eq('id',inspection.id);toast('Info saved');await loadAssessments()}
async function deleteAssessment(id){
 if(!confirm('Delete this assessment and related items/categories/work orders?'))return;
 const {data:cats}=await db.from('assessment_categories').select('id').eq('assessment_id',id);const catIds=(cats||[]).map(c=>c.id);
 if(catIds.length){const {data:items}=await db.from('assessment_items').select('id').in('category_id',catIds);const itemIds=(items||[]).map(i=>i.id);if(itemIds.length)await db.from('work_orders').delete().in('assessment_item_id',itemIds);await db.from('assessment_items').delete().in('category_id',catIds)}
 await db.from('assessment_categories').delete().eq('assessment_id',id);await db.from('assessments').delete().eq('id',id);
 if(inspection?.id===id){inspection=null;$('editor').classList.add('hidden');$('emptyEditor').classList.remove('hidden')}
 toast('Assessment deleted');await loadAssessments();setView('listView')
}
function statusDefaults(s){return s==='Good'?{risk:0,hours:0}:s==='Monitor'?{risk:2,hours:.25}:s==='Service Soon'?{risk:4,hours:.75}:{risk:7,hours:1.5}}
function renderItem(){const item=flat[current],ex=savedItems[current]||{};$('sectionTitle').textContent=item.cat;$('categoryLabel').textContent=item.cat;$('itemTitle').textContent=item.title;$('educationText').textContent=item.education;$('itemCounter').textContent=`Item ${current+1} of ${flat.length}`;$('bar').style.width=(current/flat.length*100)+'%';document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b.dataset.status===(ex.status||'')));$('riskPoints').value=ex.risk_points??0;$('estimatedHours').value=ex.estimated_hours??0;$('costRange').value=ex.cost_range||'';$('workOrderNeeded').value=ex.work_order_needed?'Yes':'No';$('observation').value=ex.observation||'';$('recommendation').value=ex.recommendation||item.defaultRec;updateScorePreview()}
function chooseStatus(s){const d=statusDefaults(s);$('riskPoints').value=d.risk;$('estimatedHours').value=d.hours;$('workOrderNeeded').value=s==='Needs Repair'?'Yes':'No';document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b.dataset.status===s));updateScorePreview()}
async function saveItem(){const item=flat[current],active=document.querySelector('.choice.active'),status=active?active.dataset.status:'Good',payload={category_id:categoryIds[item.cat],title:item.title,status,risk_points:Number($('riskPoints').value)||0,estimated_hours:Number($('estimatedHours').value)||0,observation:$('observation').value,homeowner_education:item.education,recommendation:$('recommendation').value,cost_range:$('costRange').value,work_order_needed:$('workOrderNeeded').value==='Yes',sort_order:current};let data,error;if(savedItems[current]?.id)({data,error}=await db.from('assessment_items').update(payload).eq('id',savedItems[current].id).select().single());else({data,error}=await db.from('assessment_items').insert(payload).select().single());if(error){alert(error.message);return false}savedItems[current]=data;await updateAssessmentTotals();toast('Item saved');return true}
async function next(){if(await saveItem()){if(current<flat.length-1){current++;renderItem()}else finishInspection()}}
function prev(){if(current>0){current--;renderItem()}}
function calcTotals(){const items=Object.values(savedItems),risk=items.reduce((s,i)=>s+(Number(i.risk_points)||0),0),hours=items.reduce((s,i)=>s+(Number(i.estimated_hours)||0),0),score=Math.max(0,100-risk),riskIndex=risk<=8?'Low':risk<=20?'Moderate':'High';return{items,risk,hours,score,riskIndex,wo:items.filter(i=>i.work_order_needed).length}}
function updateScorePreview(){$('score').textContent=calcTotals().score}
async function updateAssessmentTotals(){const t=calcTotals();$('score').textContent=t.score;await db.from('assessments').update({home_health_score:t.score,risk_index:t.riskIndex,estimated_hours:t.hours}).eq('id',inspection.id);finishInspection();await loadAssessments()}
function finishInspection(){const t=calcTotals();$('finalScore').textContent=t.score;$('finalRisk').textContent=t.riskIndex;$('finalHours').textContent=t.hours.toFixed(1);$('finalWO').textContent=t.wo}
function generateReport(){const t=calcTotals();let txt=`Bear Home Management - Home Health Assessment\n\nHome Health Score: ${t.score}\nRisk Index: ${t.riskIndex}\nEstimated Home Care Hours: ${t.hours.toFixed(1)}\nWork Orders Recommended: ${t.wo}\n\nFindings:\n`;t.items.filter(i=>i.status!=='Good').forEach(i=>{txt+=`\n[${i.status}] ${i.title}\nObservation: ${i.observation||'No observation entered.'}\nWhy it matters: ${i.homeowner_education}\nRecommendation: ${i.recommendation}\nCost range: ${i.cost_range||'TBD'}\n`});$('reportText').value=txt;db.from('assessments').update({summary:txt,status:'complete'}).eq('id',inspection.id);toast('Report updated')}
async function createWorkOrders(){const t=calcTotals();for(const i of t.items.filter(x=>x.work_order_needed)){const {data:existing}=await db.from('work_orders').select('id').eq('assessment_item_id',i.id);if(!existing?.length)await db.from('work_orders').insert({property_id:propertyId,assessment_item_id:i.id,title:i.title,description:i.observation,priority:i.risk_points>=7?'high':'normal',status:'open',estimated_hours:i.estimated_hours,estimated_cost:i.cost_range})}toast('Work orders created')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>chooseStatus(b.dataset.status));$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('startBtn').onclick=startInspection;$('saveItemBtn').onclick=saveItem;$('nextBtn').onclick=next;$('prevBtn').onclick=prev;$('generateReportBtn').onclick=generateReport;$('createWorkOrdersBtn').onclick=createWorkOrders;$('saveMetaBtn').onclick=saveMeta;$('deleteAssessmentBtn').onclick=()=>deleteAssessment(inspection.id);$('refreshBtn').onclick=loadAssessments;checkSession();

window.openAssessment=openAssessment;
window.deleteAssessment=deleteAssessment;
